
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('resume').del()
    .then(function () {
      // Inserts seed entries
      return knex('resume').insert([{
        "smoking": false,
        "pets": 4
      }, {
        "smoking": false,
        "pets": 1
      }, {
        "smoking": true,
        "pets": 3
      }, {
        "smoking": true,
        "pets": 1
      }, {
        "smoking": false,
        "pets": 2
      }, {
        "smoking": true,
        "pets": 3
      }, {
        "smoking": false,
        "pets": 1
      }, {
        "smoking": true,
        "pets": 2
      }, {
        "smoking": false,
        "pets": 2
      }, {
        "smoking": false,
        "pets": 4
      }, {
        "smoking": false,
        "pets": 3
      }, {
        "smoking": false,
        "pets": 2
      }, {
        "smoking": true,
        "pets": 1
      }, {
        "smoking": false,
        "pets": 3
      }, {
        "smoking": false,
        "pets": 3
      }, {
        "smoking": false,
        "pets": 3
      }, {
        "smoking": false,
        "pets": 2
      }, {
        "smoking": true,
        "pets": 1
      }, {
        "smoking": true,
        "pets": 2
      }, {
        "smoking": false,
        "pets": 1
      }, {
        "smoking": true,
        "pets": 4
      }, {
        "smoking": false,
        "pets": 1
      }, {
        "smoking": false,
        "pets": 1
      }, {
        "smoking": false,
        "pets": 4
      }, {
        "smoking": false,
        "pets": 3
      }, {
        "smoking": false,
        "pets": 2
      }, {
        "smoking": false,
        "pets": 1
      }, {
        "smoking": true,
        "pets": 4
      }, {
        "smoking": false,
        "pets": 4
      }, {
        "smoking": true,
        "pets": 2
      }, {
        "smoking": true,
        "pets": 1
      }, {
        "smoking": true,
        "pets": 1
      }, {
        "smoking": false,
        "pets": 3
      }, {
        "smoking": true,
        "pets": 2
      }, {
        "smoking": true,
        "pets": 1
      }, {
        "smoking": true,
        "pets": 4
      }, {
        "smoking": true,
        "pets": 2
      }, {
        "smoking": true,
        "pets": 2
      }, {
        "smoking": true,
        "pets": 1
      }, {
        "smoking": false,
        "pets": 4
      }, {
        "smoking": false,
        "pets": 4
      }, {
        "smoking": false,
        "pets": 3
      }, {
        "smoking": false,
        "pets": 2
      }, {
        "smoking": false,
        "pets": 4
      }, {
        "smoking": true,
        "pets": 4
      }, {
        "smoking": false,
        "pets": 2
      }, {
        "smoking": true,
        "pets": 4
      }, {
        "smoking": true,
        "pets": 1
      }, {
        "smoking": true,
        "pets": 3
      }, {
        "smoking": true,
        "pets": 4
      }, {
        "smoking": false,
        "pets": 2
      }, {
        "smoking": false,
        "pets": 3
      }, {
        "smoking": true,
        "pets": 3
      }, {
        "smoking": true,
        "pets": 1
      }, {
        "smoking": false,
        "pets": 2
      }, {
        "smoking": true,
        "pets": 1
      }, {
        "smoking": true,
        "pets": 2
      }, {
        "smoking": true,
        "pets": 2
      }, {
        "smoking": false,
        "pets": 4
      }, {
        "smoking": false,
        "pets": 1
      }, {
        "smoking": false,
        "pets": 4
      }, {
        "smoking": false,
        "pets": 4
      }, {
        "smoking": true,
        "pets": 3
      }, {
        "smoking": false,
        "pets": 1
      }, {
        "smoking": true,
        "pets": 2
      }, {
        "smoking": true,
        "pets": 3
      }, {
        "smoking": true,
        "pets": 2
      }, {
        "smoking": true,
        "pets": 3
      }, {
        "smoking": true,
        "pets": 2
      }, {
        "smoking": false,
        "pets": 1
      }, {
        "smoking": false,
        "pets": 2
      }, {
        "smoking": false,
        "pets": 1
      }, {
        "smoking": false,
        "pets": 3
      }, {
        "smoking": true,
        "pets": 3
      }, {
        "smoking": true,
        "pets": 2
      }, {
        "smoking": false,
        "pets": 3
      }, {
        "smoking": true,
        "pets": 4
      }, {
        "smoking": true,
        "pets": 2
      }, {
        "smoking": true,
        "pets": 4
      }, {
        "smoking": false,
        "pets": 4
      }, {
        "smoking": false,
        "pets": 4
      }, {
        "smoking": false,
        "pets": 3
      }, {
        "smoking": true,
        "pets": 3
      }, {
        "smoking": false,
        "pets": 1
      }, {
        "smoking": true,
        "pets": 2
      }, {
        "smoking": true,
        "pets": 3
      }, {
        "smoking": false,
        "pets": 1
      }, {
        "smoking": true,
        "pets": 3
      }, {
        "smoking": false,
        "pets": 4
      }, {
        "smoking": true,
        "pets": 3
      }, {
        "smoking": true,
        "pets": 2
      }, {
        "smoking": false,
        "pets": 1
      }, {
        "smoking": false,
        "pets": 2
      }, {
        "smoking": false,
        "pets": 2
      }, {
        "smoking": true,
        "pets": 4
      }, {
        "smoking": true,
        "pets": 2
      }, {
        "smoking": false,
        "pets": 2
      }, {
        "smoking": false,
        "pets": 3
      }, {
        "smoking": true,
        "pets": 4
      }, {
        "smoking": true,
        "pets": 4
      }]);
    });
};
