
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('features').del()
    .then(function () {
      // Inserts seed entries
      return knex('features').insert(
        [{
          "bed_room": 4,
          "baths_room": 3,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 6,
          "baths_room": 2,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 5,
          "baths_room": 7,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 9,
          "baths_room": 1,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 4,
          "baths_room": 7,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 3,
          "baths_room": 9,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 1,
          "baths_room": 10,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 3,
          "baths_room": 2,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 2,
          "baths_room": 8,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 1,
          "baths_room": 3,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 9,
          "baths_room": 9,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 1,
          "baths_room": 9,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 3,
          "baths_room": 10,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 4,
          "baths_room": 4,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 6,
          "baths_room": 7,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 9,
          "baths_room": 2,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 9,
          "baths_room": 9,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 2,
          "baths_room": 1,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 4,
          "baths_room": 9,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 3,
          "baths_room": 3,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 6,
          "baths_room": 7,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 8,
          "baths_room": 10,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 4,
          "baths_room": 7,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 7,
          "baths_room": 10,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 1,
          "baths_room": 3,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 5,
          "baths_room": 9,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 2,
          "baths_room": 5,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 9,
          "baths_room": 8,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 8,
          "baths_room": 5,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 2,
          "baths_room": 4,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 7,
          "baths_room": 6,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 5,
          "baths_room": 5,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 5,
          "baths_room": 9,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 10,
          "baths_room": 8,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 1,
          "baths_room": 1,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 2,
          "baths_room": 2,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 9,
          "baths_room": 6,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 9,
          "baths_room": 6,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 2,
          "baths_room": 10,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 2,
          "baths_room": 7,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 7,
          "baths_room": 1,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 3,
          "baths_room": 7,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 9,
          "baths_room": 3,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 2,
          "baths_room": 10,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 6,
          "baths_room": 8,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 1,
          "baths_room": 3,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 2,
          "baths_room": 3,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 10,
          "baths_room": 5,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 10,
          "baths_room": 8,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 6,
          "baths_room": 6,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 10,
          "baths_room": 2,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 6,
          "baths_room": 8,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 3,
          "baths_room": 8,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 9,
          "baths_room": 1,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 3,
          "baths_room": 9,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 10,
          "baths_room": 2,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 4,
          "baths_room": 6,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 5,
          "baths_room": 10,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 4,
          "baths_room": 9,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 5,
          "baths_room": 2,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 5,
          "baths_room": 1,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 5,
          "baths_room": 10,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 5,
          "baths_room": 4,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 3,
          "baths_room": 9,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 6,
          "baths_room": 4,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 6,
          "baths_room": 7,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 3,
          "baths_room": 1,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 8,
          "baths_room": 4,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 1,
          "baths_room": 9,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 6,
          "baths_room": 3,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 1,
          "baths_room": 1,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 8,
          "baths_room": 10,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 5,
          "baths_room": 3,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 10,
          "baths_room": 3,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 10,
          "baths_room": 4,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 2,
          "baths_room": 2,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 8,
          "baths_room": 10,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 1,
          "baths_room": 10,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 8,
          "baths_room": 4,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 8,
          "baths_room": 3,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 6,
          "baths_room": 3,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 5,
          "baths_room": 10,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 4,
          "baths_room": 10,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 3,
          "baths_room": 7,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 10,
          "baths_room": 8,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 8,
          "baths_room": 5,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 2,
          "baths_room": 7,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 8,
          "baths_room": 2,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 7,
          "baths_room": 9,
          "coop": true,
          "additional_storage": true
        }, {
          "bed_room": 5,
          "baths_room": 1,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 7,
          "baths_room": 9,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 4,
          "baths_room": 6,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 4,
          "baths_room": 8,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 8,
          "baths_room": 4,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 9,
          "baths_room": 1,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 6,
          "baths_room": 9,
          "coop": false,
          "additional_storage": false
        }, {
          "bed_room": 8,
          "baths_room": 4,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 8,
          "baths_room": 10,
          "coop": false,
          "additional_storage": true
        }, {
          "bed_room": 2,
          "baths_room": 1,
          "coop": true,
          "additional_storage": false
        }, {
          "bed_room": 4,
          "baths_room": 8,
          "coop": true,
          "additional_storage": true
        }]
      );
    });
};
